# Generated by Django 4.1.5 on 2023-02-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCelu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celulares',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
