# Generated by Django 4.1.5 on 2023-02-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCelu', '0002_alter_celulares_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell_phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('description', models.JSONField()),
                ('url_web', models.CharField(max_length=300)),
                ('url_image', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Celulares',
        ),
    ]
