# Generated by Django 4.1.5 on 2023-02-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCelu', '0003_cell_phones_delete_celulares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell_phones',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
