# Generated by Django 4.1.5 on 2023-02-05 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiCelu', '0008_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell_phones',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='apiCelu.brands'),
        ),
    ]
