# Generated by Django 4.1.5 on 2023-02-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiCelu', '0009_cell_phones_brand_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('description', models.JSONField()),
                ('url_web', models.CharField(max_length=300)),
                ('url_image', models.CharField(max_length=300)),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='apiCelu.brands')),
            ],
        ),
    ]
