# Generated by Django 4.1.5 on 2023-02-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCelu', '0011_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(),
        ),
    ]
