# Generated by Django 4.1.5 on 2023-02-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCelu', '0012_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
    ]
