# Generated by Django 4.1.5 on 2023-02-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCelu', '0013_alter_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell_phones',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='brand_id',
        ),
        migrations.AddField(
            model_name='cell_phones',
            name='brand_name',
            field=models.CharField(default='--', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='brand_name',
            field=models.CharField(default='alba', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
