# Generated by Django 4.1.5 on 2023-02-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCelu', '0014_remove_cell_phones_brand_id_remove_products_brand_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cell_phones',
        ),
    ]
