# Generated by Django 4.1.5 on 2023-02-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCelu', '0015_delete_cell_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand_name',
            field=models.CharField(max_length=100),
        ),
    ]
